"""Plain-language summary of a preview ("consultation notes").

The point is to stop a user reading a slider position as a promise. The notes
restate what the image editor actually did, what the identity signal means, and
what questions to ask a qualified practitioner.

The summary is generated by Claude when an API key is configured. With no key,
no network, or any API failure, a deterministic template is used instead - the
app never depends on the model being reachable, and no test ever calls it.
"""

from __future__ import annotations

import json
import logging
import os
from dataclasses import dataclass

from .config import DISCLAIMER, Settings, get_settings
from .identity import EXPLANATION as IDENTITY_EXPLANATION

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """You write short, honest notes for a cosmetic-preview proof of concept.

The tool applies image filters and warps to a photo. It does not model biology, \
does not predict treatment results, and is not a medical device.

Rules, without exception:
- Never state or imply a clinical outcome, a result duration, or a guarantee.
- Never recommend, dose, price, or name a specific product, drug, or injectable.
- Never comment on the person's appearance, attractiveness, age, or health.
- Describe only what the image edit did, in neutral language.
- Always tell the reader the preview is an illustration and that any real \
procedure needs a qualified practitioner.
- No diagnosis, no reassurance about safety.

Write 3 short paragraphs, under 160 words total, plain prose, no headings, no lists."""

# Opus 5 thinks by default and thinking tokens count against max_tokens, so this
# is well above what ~160 words of prose needs.
MAX_TOKENS = 2048


@dataclass(frozen=True)
class Narrative:
    """A generated or templated summary, with its provenance."""

    text: str
    source: str  # "claude" | "template"
    detail: str = ""

    @property
    def generated(self) -> bool:
        return self.source == "claude"


def narrator_available(settings: Settings | None = None) -> bool:
    """True when a Claude-generated summary could be produced."""
    settings = settings or get_settings()
    if not settings.narrator_enabled:
        return False
    if not (os.environ.get("ANTHROPIC_API_KEY") or os.environ.get("ANTHROPIC_AUTH_TOKEN")):
        return False
    try:
        import anthropic  # noqa: F401
    except Exception:
        return False
    return True


def _template(summary: dict[str, object]) -> str:
    treatments = summary.get("treatments") or []
    if treatments:
        described = ", ".join(
            f"{t['label'].lower()} at {t['intensity']}%"
            for t in treatments  # type: ignore[index]
        )
        first = (
            f"This preview applied {described}. Those are image edits - filters and "
            "geometric warps over the detected face region - not a simulation of any "
            "biological process."
        )
    else:
        first = (
            "No treatment was applied, so the two images are identical. Move a slider "
            "to see what an edit at that strength looks like."
        )

    identity = summary.get("identity")
    if identity:
        second = (
            f"The identity signal (SSIM) reads {identity['ssim']:.3f} against a "  # type: ignore[index]
            f"threshold of {identity['threshold']:.2f} - {identity['verdict'].lower()}. "  # type: ignore[index]
            "That measures how much image structure changed; it is not an identity "
            "match and it says nothing about whether the edit is realistic."
        )
    else:
        second = (
            "No identity signal was computed for this image, so there is no measure of "
            "how much structure the edit changed."
        )

    third = (
        "Treat this as a conversation starter, not a plan. Anything you are actually "
        "considering should be discussed with a qualified practitioner who can examine "
        "you in person and explain risks, alternatives and realistic expectations."
    )
    return "\n\n".join([first, second, third])


def summarise(summary: dict[str, object], settings: Settings | None = None) -> Narrative:
    """Return consultation notes for a preview summary.

    ``summary`` is the dict produced by :func:`src.pipeline.describe_result`.
    """
    settings = settings or get_settings()
    fallback = Narrative(_template(summary), "template", "No model call was made.")
    if not narrator_available(settings):
        return fallback

    try:
        import anthropic

        client = anthropic.Anthropic()
        response = client.beta.messages.create(
            model=settings.narrator_model,
            max_tokens=MAX_TOKENS,
            system=SYSTEM_PROMPT,
            output_config={"effort": "low"},
            betas=["server-side-fallback-2026-07-01"],
            fallbacks="default",
            messages=[
                {
                    "role": "user",
                    "content": (
                        "Preview summary (JSON):\n"
                        f"{json.dumps(summary, indent=2)}\n\n"
                        f"How the identity signal works: {IDENTITY_EXPLANATION}\n\n"
                        "Write the notes."
                    ),
                }
            ],
        )
        stop_reason = getattr(response, "stop_reason", None)
        if stop_reason == "refusal":
            logger.info("Narrator request was declined; using the template.")
            return Narrative(fallback.text, "template", "The model declined this request.")
        if stop_reason == "max_tokens":
            logger.info("Narrator response was truncated; using the template.")
            return Narrative(fallback.text, "template", "The model response was truncated.")
        text = "\n".join(
            block.text for block in response.content if getattr(block, "type", "") == "text"
        ).strip()
        if not text:
            return Narrative(fallback.text, "template", "Empty model response.")
        return Narrative(f"{text}\n\n{DISCLAIMER}", "claude")
    except Exception as exc:
        logger.warning("Narrator unavailable (%s); using the template.", exc)
        return Narrative(fallback.text, "template", f"Model call failed: {exc}")
